#!/usr/bin/env python3
"""
Scaffolding CLI tool to quickly add new subjects to prep.
Usage:
    python3 tools/create_subject.py --id python --label "Python & Data Science" --short "Python"
"""

import argparse
import sys
from pathlib import Path

DEFAULT_ICON = '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"></path></svg>'

DATA_FILE_TEMPLATE = """// {label} ({subject_id}) Subject Data & MCQs
// Generated by tools/create_subject.py

const {upper_id}_STUDY_DATA = {{
  unit1: {{
    unitName: "Unit 1 — Introduction to {label}",
    topics: [
      {{
        title: "Getting Started with {label}",
        content: `
          <h3>Overview of {label}</h3>
          <p>Welcome to {label}. This section covers core fundamentals, key concepts, and practical examples.</p>
          <div class="callout callout-info">
            <strong>Key Concept:</strong> Master the basics before moving to advanced topics.
          </div>
        `
      }}
    ]
  }}
}};

const {upper_id}_MCQ_BANK = [
  {{
    unitName: "Unit 1 Practice Quiz",
    examGroup: "unit1",
    questions: [
      {{
        id: {start_id},
        topic: "Fundamentals",
        question: "What is a primary characteristic of {label}?",
        options: {{
          a: "High versatility and ease of use",
          b: "Hardware exclusive execution",
          c: "Deprecated syntax",
          d: "Single-line execution limit"
        }},
        correct: "a",
        explanation: "{label} emphasizes readability, versatility, and efficiency."
      }}
    ]
  }}
];
"""

CONFIG_SNIPPET_TEMPLATE = """
// Add this entry inside CONFIG.subjects in IOT/app.js:
{subject_id}: {{
  label: "{label}",
  shortLabel: "{short_label}",
  icon: '{icon}',
  examTime: null,
  storageKey: "{subject_id}_mastered_topics",
  storageKeyPractice: "{subject_id}_mcq_answers",
  scripts: ["{file_name}"],
  data: {{}},
  mcqs: null,
  themeColors: {{
    unit1: '#5F7AE0',
    practice: '#8C4735'
  }},
  sectionNames: {{
    unit1: 'Unit 1 — Fundamentals',
    practice: 'Topic-Wise MCQs'
  }},
  tabs: [
    {{ id: 'unit1', label: 'Unit 1' }},
    {{ id: 'practice', label: 'MCQs' }}
  ]
}}
"""

def main():
    parser = argparse.ArgumentParser(description="Scaffold a new subject for prep hub.")
    parser.add_argument("--id", required=True, help="Unique identifier for the subject (e.g. python, dbms, os)")
    parser.add_argument("--label", required=True, help="Full display label (e.g. 'Operating Systems')")
    parser.add_argument("--short", help="Short label for buttons (e.g. 'OS'). Defaults to --label if omitted.")
    parser.add_argument("--icon", default=DEFAULT_ICON, help="SVG string for subject icon.")

    args = parser.parse_args()

    subject_id = args.id.lower().strip()
    label = args.label.strip()
    short_label = (args.short or label).strip()
    upper_id = subject_id.upper()
    file_name = f"{subject_id}-data.js"
    
    target_dir = Path(__file__).resolve().parent.parent / "IOT"
    target_file = target_dir / file_name

    if target_file.exists():
        print(f"Error: Target file {target_file} already exists!")
        sys.exit(1)

    start_id = hash(subject_id) % 8000 + 4000
    
    file_content = DATA_FILE_TEMPLATE.format(
        label=label,
        subject_id=subject_id,
        upper_id=upper_id,
        start_id=abs(start_id)
    )

    target_file.write_text(file_content, encoding="utf-8")
    print(f"✓ Created subject data file: {target_file}")
    print("\n--- CONFIG SNIPPET ---")
    print(CONFIG_SNIPPET_TEMPLATE.format(
        subject_id=subject_id,
        label=label,
        short_label=short_label,
        icon=args.icon,
        file_name=file_name
    ))

if __name__ == "__main__":
    main()
